import = "theme.toml"

prompt = "{username}@{hostname}: {cwd} {git_branch} {git_status}\n{character} "
prompt_right = "{time}"
add_newline = true

[hostname]
format = "^(sapphire){hostname}^"

[username]
format = "^(peach){username}^"

[cwd]
format = '^(lavender){cwd}^'
max_length = 3

[time]
format = '^(subtext0){time}^'
time_format = "15:04:05"

[character]
icon = 'λ'
format = '^(peach){character}^'

[git_branch]
format = '^(yellow)on^ ^(mauve) {branch}^'

[git_status]
format = '^(red)[^{status}^(red)]^'
clean_suffix = ''
conflicted = '^(red)✖^'
ahead = '^(red)⇡^'
behind = '^(red)⇣^'
diverged = '^(red)⇕^'
up_to_date = '^(red)✓^'
untracked = '^(red)?^'
stashed = '^(red)S^'
modified = '^(red)~^'
staged = '^(red)+^'
renamed = '^(red)»^'
deleted = '^(red)✘^'
